name: e2e
on: [push, pull_request]
jobs:
  playwright-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Chrome stable
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget gnupg ca-certificates
          wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable
      - name: Backend (sqlite)
        run: |
          cd backend
          npm ci
          USE_SQLITE=1 JWT_SECRET=dev_jwt_secret PORT=4000 nohup node src/server.js >/tmp/api.log 2>&1 &
          for i in {1..40}; do curl -fsS http://127.0.0.1:4000/health >/dev/null && break; sleep 1; done
          curl -fsS http://127.0.0.1:4000/health
      - name: Frontend dev server
        run: |
          cd frontend
          npm ci
          REACT_APP_API_URL=http://127.0.0.1:4000 HOST=0.0.0.0 PORT=3000 BROWSER=none nohup npm start >/tmp/front.log 2>&1 &
          for i in {1..60}; do curl -fsS http://127.0.0.1:3000 >/dev/null && break; sleep 1; done
          curl -fsS http://127.0.0.1:3000
      - name: Run Playwright E2E (use system Chrome)
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
          PW_CHROMIUM_PATH: "/usr/bin/google-chrome-stable"
          E2E_BASE_URL: "http://127.0.0.1:3000"
          E2E_API_BASE: "http://127.0.0.1:4000"
        run: |
          cd frontend
          npx playwright --version
          npm run e2e
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            /tmp/api.log
            /tmp/front.log
